### ISSUE TITLE
question for account : password of default user "confluence" and "root"

### ISSUE THREAD

**Issue by av930** [blacklabelops/confluence#10]
1st try: run stop-confluence.sh, it fails in sub scripts, in result, I think it needs permission "su -"
2nd try: su fails, the error pops up "must be suid to work properly", when trying to change account and similar jobs, I think this is from busybox configuration.
3rd try: try to something more, but need root permission...

**I'd like to know password of default user "confluence" and "root".**

**Comment by blacklabelops** [comment]
This is a Dockerized Confluence image.

You start one container with `docker run ...`

You stop the container with `docker stop ...`

You start the container again with `docker start ...`

There is no need to call the start and stop scripts.

**Comment by av930** [comment]
Ok I got it. There are some mis-understanding in how docker container works. I thought docker container become frozen when I run "docker stop" and visa versa.

**Comment by av930** [comment]
@blacklabelops  
In advance, I am thankful for your work on this confluence image.
Currently I add my modification, confluence settings and put some contents, and add some utilities.
Today I am trying to upgrade the confluence to version 6.1.1 from 6.0.4 by following this guide: 
[https://confluence.atlassian.com/doc/upgrading-confluence-4578.html#UpgradingConfluence-1.Determineyourupgradepath](https://confluence.atlassian.com/doc/upgrading-confluence-4578.html#UpgradingConfluence-1.Determineyourupgradepath) 

doing this, I cannot stop the confluence process (/opt/java/jre1.8.0_92/bin/java -Djava.util.logging.config.file=/opt/atlassian/confluence/c~)
How can I stop the process in the container? if I manually kill it, the container automatically be killed.
I think you don't expect and intend this kind of usage do like this...

The reason why I am doing this is there are some exception log and stopped frequently whenever I restart the container. therefore I decided to upgrade it by myself.

**question summary**
Q1: how can I stop confluence process without exiting container?
Q2: Is there any recommendable upgrade-methodology the existing container?

**Comment by blacklabelops** [comment]
Hello av! The update mechanism for this image is as follows: Upgrade directly to the latest version of Confluence 6.

You can do this with the following steps:

MOST IMPORTANT: Make a backup of all your Docker volumes (E.g. with [blacklabelops/volumerize](https://github.com/blacklabelops/volumerize) and don't forget your database!!

Then:

1. Pull the latest image tag: docker pull blacklabelops/confluence:your-wanted-version
1. Stop your current container: docker stop your-running-container-name
1. Remove the current container: docker rm your-running-container-name
1. Now start the container with the same command but with the new tagged image: docker run <your-runtime-parameters> blacklabelops/confluence:your-wanted-version
1. Confluence will start it's internal update mechanism and work as expected

Worst case: Update breaks or you can't use confluence because the latest version isn't working with some legacy plugins you installed. In this case: Rollback with backup!

**Comment by av930** [comment]
Thanks a lot for recent 6.1.2 push.  I will try with it.
