### ISSUE TITLE
Docker Container crashes because of no space left in volume

### ISSUE THREAD

**Issue by philippfrenzel** [blacklabelops/confluence#6]
Hi,

we have the image running, but since a couple of days, it always stops and says
volumen out of space 
the server has about 2 TB free diskspace - do you have an idea?

Can't find anything about that issue within docker :/

Thanks Philipp

**Comment by blacklabelops** [comment]
Hello,

Please check the files Confluence write into the container. Maybe your container is overflowing, because big files are written inside the container not your container volume.

~~~~
$ docker diff <yourcontainername>
~~~~

> Lists the files which change since instantiating the image from the image.

By default confluence uses `/var/atlassian/confluence` as a workfolder. This folder has to be a volume. Usually this works by default, `/var/atlassian/confluence` is defined as a volume inside the Dockerfile.

Simple example using correctly a volume with `-v` with my image:

~~~~
$ docker volume create confluence_data
$ docker run -d -v confluence_data:/var/atlassian/confluence -p 80:8090 -p 8091:8091 --name confluence blacklabelops/confluence
~~~~

> First command creates a volume and the second starts the container with the named volume.

You can also check the volume with:

~~~~
$ docker inspect <yourcontainername>
~~~~

> This will list all container details including the host volume paths

Make sure your host-volume-folder has access rights and enough space for user with the uid 1000 and gid 1000. That is the run user that is defined inside the image.

When you got more questions please:

- Post your start parameters
- Your operating system
- Docker Version

**Comment by philippfrenzel** [comment]
thanks, i'll test on sunday and let you know! ;)

**Comment by blacklabelops** [comment]
Closing issue because of missing feedback.
